version: 2

jobs:

  test:
    docker:
      - image: rust:1.38
    steps:
      - checkout
      # Load cargo target from cache if possible.
      # Multiple caches are used to increase the chance of a cache hit.
      - restore_cache:
          keys:
            - v1-cargo-cache-{{ checksum "Cargo.lock" }}
            - v1-cargo-cache-{{ .Branch }}
            - v1-cargo-cache
      - run: cargo build
      - run: cargo test
      - save_cache:
          key: v1-cargo-cache-{{ checksum "Cargo.lock" }}
          paths:
            - /usr/local/cargo
      - save_cache:
          key: v1-cargo-cache-{{ .Branch }}
          paths:
            - /usr/local/cargo
      - save_cache:
          key: v1-cargo-cache
          paths:
            - /usr/local/cargo
  lint:
    docker:
      - image: rust:1.51
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-cargo-lint-cache
      - run: rustup component add clippy
      - run: cargo clippy --all-targets --all-features -- -D warnings
      - save_cache:
          key: v1-cargo-lint-cache
          paths:
            - /usr/local/cargo
  audit:
    docker:
      - image: dbrgn/cargo-audit:latest
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: apt update && apt install -y cmake
      - run:
          name: Run cargo-audit
          command: cargo audit

workflows:
  version: 2

  # Build on push
  on_push:
    jobs:
      - test
      - lint
      - audit

  # Build master every week on Monday at 04:00 am
  weekly:
    triggers:
      - schedule:
          cron: "0 4 * * 1"
          filters:
            branches:
              only:
                - master
    jobs:
      - test
      - lint
      - audit
